# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "Monash Science Symposium 2025"
email: "mum-sciencesymposium@monash.edu"
description: "Monash Science Symposium (MSS) 2025. It is a student-led event by the School of Science postgraduate students of Monash University Malaysia (MUM)."
baseurl:
url: "https://claudeenlau.github.io/mss-2025/"
#googleAnalyticsTrackingId: "UA-181963946-1"
#googleAnalyticsSiteUrl: "monash-sciencesymposium.com"
#siteVerification: "htLClk4VKGu4DxmQigKnQQfLpjcDlpQ0whEJXEdchGE"

# Organizer Info
organizerName: "MSS"
organizerAlternateName: "Monash Science Symposium"
organizerDescription: "<em>Innovating for Tomorrow: Scientific Solutions for a Sustainable Future</em>"
organizerEmail: "mum-sciencesymposium@monash.edu"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://claudeenlau.github.io/mss-2025/"

# Head
metaKeywords: "mss, monash, science, symposium, malaysia, 2025"
twitterAccount: "@mss_mum"
socialImageSrcGooglePlus: "/img/seo/organizer-logo.png"
socialImageSrcTwitter: "/img/seo/organizer-logo.png"
socialImageSrcFacebook: "/img/seo/organizer-logo.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/about-us/", text: "About Us"}
 - {permalink: "/speakers", text: "Speakers"}
 - {permalink: "/registration", text: "Registration"}
bottomNavigationLinks:
 - {permalink: "/registration", text: "Register now"}
rightNavigationButtons:
 - {permalink: "/registration", text: "Register now"}

# Miscellaneous links
#speakerButtonRegister: "https://forms.gle/t2ztnxtMbNzzXC2o8"

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Monash Science Symposium (MSS) <typeout>"
eventDate: "15-17 July 2025"
heroMotto: "<em>Innovating for Tomorrow: Scientific Solutions for a Sustainable Future</em>"
typeoutTextValues: '"", "2025" '
typeoutFallback: ""
heroButtons:
- {permalink: "/registration", text: "Register now"}
#- {permalink: "/#footer", text: "Footer"}

# Categories Block
categoriesTitle: "Submit abstracts now"
categoriesDescription: "We will be calling for abstract submission for the following categories:"
categoriesBlock:
 - {text: "Drug Discovery & Development", image: "category_logo_drugdiscovery.png"}
 - {text: "Green & Sustainable Chemistry", image: "category_logo_greenchem.png"}
 - {text: "Tropical Biodiversity & Conservation Biology", image: "category_logo_env.png"}
 - {text: "Functional & Future Food", image: "category_logo_fst.png"}
 - {text: "Big Data Analytics & Genomics for One Health", image: "category_logo_gen.png"}
categoriesButton:
 - {permalink: "/registration", text: "Register now"}

# About MSS Block
aboutMSSBlockTitle: "About MSS"
aboutMSS: "The Monash Science Symposium (MSS) 2025 is an international academic event organized by postgraduate students at the School of Science of Monash University Malaysia (MUM). This symposium highlights a broad range of research topics and projects that reflect the university's strategic goal - Impact 2030."
objectives:
  - {objective: "Allow young scientists and postgraduate students to showcase and discuss their research."}
  - {objective: "Foster networking between local and international experts in their respective field of research."}
  - {objective: "Highlight ongoing research in Monash University Malaysia aligning with Monash Impact 2030."}

# Team Block
teamBlockTitle: "<strong>Meet the Team</strong>"

# Scientific Committee Block
scientificCommitteeBlockTitle: "Scientific Committee"

# History Block
history1: "MSS was first held in 2013 as a gathering of local science graduate research students to share and discuss their research findings. Since then, it has grown in size and scope to include the student community of other local and international universities and research institutes. True to the Monash motto “<em>Ancora Imparo</em>”, the Symposium aims to enhance the science learning experience by encouraging knowledge exchange between researchers, promoting local research work, exploring potential collaborations, and fostering closer ties with other research universities."
history2: "In 2014, the Symposium has registered more than 150 student participants, half of which represent participants from 9 other different local universities/research institutes. In 2016, the symposium was held with more registered participants, including external participants who were from 13 universities and a government agency. A new scope was introduced in MSS 2016, covering a total of 6 major life sciences branches and were presented over 3-day periods. The Symposium had received overwhelming positive feedback from the participants. In 2018, an intervarsity symposium which served as a promotional event to highlight the capabilities of HDR students of Monash University Malaysia in producing quality research outputs and the dissemination of their scientific findings to a broader audience. In 2021, the Symposium continued its legacy by expanding the event and introducing a new science category, “Science Communication and Safety.” This addition aimed to broaden the scope of the symposium and address emerging trends in the scientific community. This approach was also carried forward in 2022, with the same focus on expanding the event and strengthening this category to further engage participants and enhance the overall impact of the symposium."
history3: "For MSS 2025, we aim to host the Symposium as an international platform that brings together students, researchers, and experts from around the world. The event will feature a diverse array of research topics, showcasing the innovative work being carried out at Monash University Malaysia. Aligned with the university's Impact 2030 initiative, the Symposium will provide an opportunity for young scientists and postgraduate students to present their findings, engage in meaningful discussions, and connect with leading professionals in their respective fields. Through this event, we will highlight Monash University's ongoing contributions to global scientific advancement and foster collaboration between local and international research communities."

# Schedule Introduction Block
scheduleIntroTitle: "Schedule TEST"
scheduleIntro1: "MSS 2025 will be held for three days and be split into the morning and afternoon sessions."
scheduleIntroButtons:
  - {permalink: "/schedule/#day-1-morning", text: "Day 1 (Morning)"}
  - {permalink: "/schedule/#day-1-afternoon", text: "Day 1 (Afternoon)"}
scheduleIntro2: "Oral presentations are categorised into 7 categories:<br>1. Genomics & Bioinformatics<br>2. Cell & Molecular Biology<br>3. Chemistry & Drug Discovery"

# Guidelines Block
guidelinesTitle: "Submission Guidelines"
guidelines1: "Welcome to Monash Science Symposium (MSS) 2025! Our theme this year is “Innovating for Tomorrow: Scientific Solutions for a Sustainable Future”.
MSS 2025 will feature the following categories:"
guidelines2: "Please check out the abstract submission guidelines and the presentation guidelines below."
abstractSubmissionTitle: "Abstract Submission Guidelines"
abstractSubmissionPoints:
 - {point: "Title of the abstract should be 15 words or less and should clearly identify the focus of the abstract."}
 - {point: "Authors' names should be arranged as last name first, followed by given names."}
 - {point: "Word count: 200 words or less"}
 - {point: "All submissions must be made through the online form."}
 - {point: "The online submission process will provide further instructions regarding contact information, how to submit, etc."}
 - {point: "File format: PDF"}
guidelinesButton:
 - {link: "https://drive.google.com/file/d/1PNHtdyUTJc8vYyGB-rHQbbCoVVX63ozq/view?usp=sharing", text: "All guidelines and abstract template"}
 - {link: "https://docs.google.com/forms/d/1RGY7hAj0dqqInod1gwS8eHVzm6r32KVNumyQuWEY-0Y/viewform?edit_requested=true", text: "Online registration form (Presenter)"}
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSft4wuqm--ojabGXNILVyldJjfEs_Ro9l5cSV4VnuJKnpGrog/viewform", text: "Online registration form (Audience)"}

# Payment Guidelines Block
payGuidelinesTitle: "Payment guidelines"
payGuidelines1: "Upon online registration, participants are required to attach their abstracts in the online registration form."
payGuidelines2: "Payment in foreign currencies must be based on exchange rates at the time of payment. Upon payment, please email the banked-in receipt to us at <strong><a href=\"mailto:mum-sciencesymposium@monash.edu\">mum-sciencesymposium@monash.edu</a></strong>"
payGuidelines3: "Payment can be made via bank transfer using the details below:"
payGuidelinesPoints:
 - {point: "Beneficiary Account Name: MONASH UNIVERSITY MALAYSIA SDN BHD"}
 - {point: "Beneficiary Address: JALAN LAGOON SELATAN, BANDAR SUNWAY, 47500 PETALING JAYA, SELANGOR DARUL EHSAN"}
 - {point: "Beneficiary Account Number: 302838727101"}
 - {point: "Beneficiary Bank Name: HSBC BANK MALAYSIA BERHAD"}
 - {point: "Beneficiary Bank Address: 2 LEBOH AMPANG, 50100 KUALA LUMPUR, MALAYSIA"}
 - {point: "Beneficiary Bank Swift Code: HBMBMYKL"}
 - {point: "Beneficiary Company Registration Number: 199801002475 (458601-U)"}
 - {point: "Beneficiary Company Tax Number: C185386104"}
payGuidelines4: "Please quote <strong>\"MSS 2025\"</strong> in the bank transfer. Once payment is completed, please attach it to the registration form."
payGuidelines5: "You can also <strong>pay via credit card</strong> through the link here: <a href=\"https://fin-ebpg.monash.edu.my/online_payment.php</a>."
#need to change the link for payment
payGuidelines6: "Once you are directed to the payment page, please choose <strong>\"Monash Science Symposium (MSS) 2022\"</strong> from the drop down menu. This payment option is only accepted in <strong>MYR</strong>. If you are paying in <strong>USD</strong>, please convert it to <strong>MYR</strong> according to your bank rates before proceeding with the payment. Once payment is completed, please attach a picture showing proof of payment and send it to <strong><a href=\"mailto:mum-sciencesymposium@monash.edu\">mum-sciencesymposium@monash.edu</a></strong>"

# Key Dates Block
keyDatesBlockImage: "key-dates.jpg"
keyDates:
 - {date: "XX Month 2025", text: "Early bird deadline"}
 - {date: "XX Month 2025", text: "Standard deadline"}
 - {date: "15-17 July 2025", text: "Symposium"}

# Statistic Block
#statisticBlockImage: "statistic.jpg"
#statisticBlock:
# - {count: "15", specialCharacter: " Jan", info: "2020", detail: "Early Bird Deadline"}
# - {count: "30", specialCharacter: " Jan", info: "2020", detail: "Abstract Deadline"}
# - {count: "1", specialCharacter: " Feb", info: "2020", detail: "Registration Closes"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Monash University Malaysia"
#eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "Jalan Lagoon Selatan, Bandar Sunway"
eventAddressLocality: "47500 Subang Jaya, Selangor, Malaysia"
#eventAddressLocalityRegion: "Lv{% include about.html %}ivska"
eventPostalCode: "47500"
eventAddressCountry: "Malaysia"
eventStartTime: "8 Jan (09:00)"
#eventDoorTime: "09:00"
eventEndTime: "10 Jan (20:00)"
eventPlaceCoordinates: "3.064917, 101.600973"
mapCenterCoordinates: "3.064917, 101.600973"
mapMobileCenterCoordinates: "3.064917, 101.600973"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
partnersTitle: "Sponsors"
partnersDescription: "We would like to thank our sponsor for their generous support:"
# partnersSponsorsButton: "Become a sponsor"

# Subscribe Block
#subscribeImage: "subscribe.jpg"
#subscribeTitle: "Subscribe for updates"
#subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
#subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Ticket prices"
#ticketsInfo: "Tickets grant access to all conference sections and food. Accommodation is NOT included in the ticket price."
ticketsOffers:
-
  name: "Monash students"
  price: "100"
  priceCurrency: "MYR"
  buyButtonLink: "https://claudeenlau.github.io/mss-2025/registration/"
  buyButtonText: "<strong>Register Now</strong>"
  validFrom: "2025-XX-XXT12:00 PM"
  validThrough: "2025-XX-XXT12:00 PM"
  additionalInfo: "<i>Only for Monash students</i>"
-
  name: "Local students"
  price: "150"
  priceCurrency: "MYR"
  buyButtonLink: "https://claudeenlau.github.io/mss-2025/registration/"
  buyButtonText: "<strong>Register Now</strong>"
  validFrom: "2025-XX-XXT12:00 PM"
  validThrough: "2025-XX-XXT12:00 PM"
  additionalInfo: "<i>Only students from Malaysian universities/colleges</i>"
-
  name: "Local non-students/delegates"
  price: "175"
  priceCurrency: "MYR"
  buyButtonLink: "https://claudeenlau.github.io/mss-2025/registration/"
  buyButtonText: "<strong>Register Now</strong>"
  validFrom: "2025-XX-XXT12:00 PM"
  validThrough: "2025-XX-XXT12:00 PM"
  additionalInfo: "<i>For Malaysian non-students, delegates and participants from the industry</i>"
-
  name: "International participants"
  price: "75"
  priceCurrency: "USD"
  buyButtonLink: "https://claudeenlau.github.io/mss-2025/registration/"
  buyButtonText: "<strong>Register Now</strong>"
  validFrom: "2025-XX-XXT12:00 PM"
  validThrough: "2025-XX-XXT12:00 PM"
  additionalInfo: "<i>For international students, delegates and participants from the industry</i>"

# Footer
socialLinks:
  - {link: "https://twitter.com/mss_mum", icon: "twitter"}
  - {link: "https://linkedin.com/in/monash-science-symposium-790b301a1", icon: "linkedin"}
  - {link: "https://www.instagram.com/monash.sciencesymposium/", icon: "instagram"}
  - {link: "https://www.facebook.com/monashsciencesymposium/", icon: "facebook"}
footerBlocks:
 -
  title: "Contact"
  links:
   - {link: "mailto:mum-sciencesymposium@monash.edu", text: "Email us"}
 -
  title: "Past events"
  links:
    - {link: "https://monash-sciencesymposium.github.io/zeppelin/", text: "MSS 2022"}
    - {link: "https://monash-sciencesymposium.github.io/website-2021/", text: "MSS 2021"}
    - {link: "https://monashscience2018.jimdofree.com/", text: "MSS 2018"}
    - {link: "https://monashscience.jimdofree.com/", text: "MSS 2016"}


# Sponsorship Tiers Block
sponsorshipTiersTitle: "Sponsorship Tiers"
sponorshipTiersNote1: "*If you are only interested in selling merchandise (minimum 200 pieces), which comes with an acknowledgement in the program booklet, please contact _________"
sponorshipTiersNote2: "*Note that the program booklets will be hardcopies for distinguished guests and softcopies for participants"
sponsorshipTiers:
 -
  name: "Bronze"
  benefitList: ["Acknowledgement in program booklet", "Advertisement on TV screens throughout the Monash campus (every 20 minutes)", "Logos on photo booths"]
  headerBackgroundColor: "rgb(142,112,104,0.4)"
  headerTextColor: "#333333"
 -
  name: "Silver"
  benefitList: ["Quarter-page advertisement in program booklet", "Advertisement on TV screens throughout the Monash campus (every 20 minutes)", "Logos on photo booths and banners", "Shoutouts on social media platforms once every fortnight (Facebook, Instagram, Twitter)", "Acknowledgement of company on website"]
  headerBackgroundColor: "rgb(141,198,197,0.4)"
  headerTextColor: "#333333"
 -
  name: "Gold"
  benefitList: ["Half-page advertisement in program booklet", "Advertisement on TV screens throughout the Monash campus (every 20 minutes)", "Logos on photo booths and banners", "Shoutouts on social media platforms once a week (Facebook, Instagram, Twitter)", "Acknowledgement of company on website", "Shared booth for 3 days"]
  headerBackgroundColor: "rgb(255,206,0,1.0)"
  headerTextColor: "#333333"
 -
  name: "Platinum"
  benefitList: ["Full-page advertisement in program booklet", "Advertisement on TV screens throughout the Monash campus (every 20 minutes)", "Logos on photo booths and banners", "Shoutouts on social media platforms twice a week (Facebook, Instagram, Twitter)", "Acknowledgement of company on website", "Largest exhibition booth for 3 days", "Logo printed on pendrives which will be given to all participants", "Industrial speaker of company’s choice"]
  headerBackgroundColor: "rgb(211,21,91,1.0)"
  headerTextColor: "#ffffff"

# Speakers List Block
showSessions: false

# Logistics Find Way Block
# findWayTitle: "Find your way here"
# findWayDistance: "Distance"
# findWayDriving: "DRIVING"
# findWayWalking: "WALKING"
# findWayBicycling: "BICYCLING"
# findWayTransit: "TRANSIT"
# findWayFindFlight: "Find Flight"
# logisticsMapCenterCoordinates: "49.056728, 3.117289"
# logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
# logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsTitle: "Sunway City"
directionDetailsDescription: "Monash University Malaysia is located in Bandar Sunway (Sunway City), a township equipped with leisure, entertainment, educaiton and residential facilities. You can commute around Sunway City through a few options below:"
directionDetailsCards:
  -
    title: "Canopy Walk"
    information: "The canopy walk is an elevated and secure (monitored by close-circuit television cameras) walkway in Bandar Sunway that connects our campus to the Sunway Pyramid mall. The walk takes about 15-20 minutes. For more information, check out our <a href=\"https://drive.google.com/open?id=1DWHKEqD5RvDFFdRzlTYaCNNvKuY7ylkK&usp=sharing\">custom Google Map.</a>"
  -
    title: "BRT"
    information: "The game-changing Bus Rapid Transit (BRT) is Malaysia's first elevated Bus Rapid Transit system. This BRT Sunway line connects Sunway City with other public rail transportion (Setia Jaya KTM Komuter station and the USJ7 LRT station). Check out this <a href=\"https://www.malaysia-traveller.com/BRT-Sunway.html\">travel blog</a> for more information."
  -
    title: "Shuttle Bus"
    information: "The free Sunway Shuttble Bus service runs every 60 minutes (subject to traffic conditions). From Monday to Saturday, it operates from 7:00 AM - 10:15 PM. On Sundays, it's 9:00 AM - 10:15 PM. Please click <a href=\"https://drive.google.com/a/monash.edu/file/d/1qTRcUGG0i-Bhrq0HcJlEiFLqCrWQDa0Q/view?usp=sharing\">here for the list of bus stops.</a>"
  -
    title: "Grab"
    information: "Grab is one of Malaysia's most well-known ride-hailing services. Fares may vary depending on traffic and weather conditions. The Grab app is available on <a href=\"https://www.grab.com/my/download/\">App Store and Google Play.</a>"
