# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "Monash Science Symposium 2025"
email: "mum-sciencesymposium@monash.edu"
description: "Monash Science Symposium (MSS) 2025. It is a student-led event by the School of Science postgraduate students of Monash University Malaysia (MUM)."
baseurl:
url: "https://claudeenlau.github.io/mss-2025/"
#googleAnalyticsTrackingId: "UA-181963946-1"
#googleAnalyticsSiteUrl: "monash-sciencesymposium.com"
#siteVerification: "htLClk4VKGu4DxmQigKnQQfLpjcDlpQ0whEJXEdchGE"

# Organizer Info
organizerName: "MSS"
organizerAlternateName: "Monash Science Symposium"
organizerDescription: "<em>Innovating for Tomorrow: Scientific Solutions for a Sustainable Future</em>"
organizerEmail: "mum-sciencesymposium@monash.edu"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://claudeenlau.github.io/mss-2025/"

# Head
metaKeywords: "mss, monash, science, symposium, malaysia, 2025"
twitterAccount: "@mss_mum"
socialImageSrcGooglePlus: "/img/seo/organizer-logo.png"
socialImageSrcTwitter: "/img/seo/organizer-logo.png"
socialImageSrcFacebook: "/img/seo/organizer-logo.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/about-us/", text: "About Us"}
 - {permalink: "/speakers", text: "Speakers"}
 - {permalink: "/registration", text: "Registration"}
 - {permalink: "/sponsors/", text: "Sponsors"}
bottomNavigationLinks:
 - {link: "https://shop.monash.edu.my/monash-science-symposium-2025.html", text: "Register now"}
rightNavigationButtons:
 - {link: "https://shop.monash.edu.my/monash-science-symposium-2025.html", text: "Register now"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Monash Science Symposium (MSS) <typeout>"
eventDate: "15-17 July 2025"
heroMotto: "<em>Innovating for Tomorrow: Scientific Solutions for a Sustainable Future</em>"
typeoutTextValues: '"", "2025" '
typeoutFallback: ""
heroButtons:
- {link: "https://shop.monash.edu.my/monash-science-symposium-2025.html", text: "Register now"}
#- {permalink: "/#footer", text: "Footer"}

original sites categories block:
# Categories Block
categoriesTitle: "Abstract submissions closed!"
categoriesDescription: "Abstract submission categories:"
categoriesBlock:
 - {title: "Applied Microbiology", image: "category_logo_microbio.png"}
 - {title: "Cell & Molecular Biology", image: "category_logo_bio.png"}
 - {title: "Green & Sustainable Chemistry", image: "category_logo_greenchem.png"}
 - {title: "Environmental & Agricultural Sciences", image: "category_logo_env.png"}
 - {title: "Food Science & Technology", image: "category_logo_fst.png"}
 - {title: "Genomics & Bioinformatics", image: "category_logo_gen.png"}
categoriesButton:
 - {link: "https://shop.monash.edu.my/monash-science-symposium-2025.html", text: "Register now"}

# About MSS Block
aboutMSSBlockTitle: "About MSS"
aboutMSS: "The Monash Science Symposium (MSS) 2025 is an international academic event organized by postgraduate students at the School of Science of Monash University Malaysia (MUM). This symposium highlights a broad range of research topics and projects that reflect the university's strategic goal - Impact 2030."
objectives:
  - {objective: "Allow young scientists and postgraduate students to showcase and discuss their research."}
  - {objective: "Foster networking between local and international experts in their respective field of research."}
  - {objective: "Highlight ongoing research in Monash University Malaysia aligning with Monash Impact 2030."}

# Team Block
teamBlockTitle: "Meet the Team"

# Scientific Committee Block
scientificCommitteeBlockTitle: "Scientific Committee"

# History Block
history1: "MSS was first held in 2013 as a gathering of local science graduate research students to share and discuss their research findings. Since then, it has grown in size and scope to include the student community of other local and international universities and research institutes. True to the Monash motto “<em>Ancora Imparo</em>”, the Symposium aims to enhance the science learning experience by encouraging knowledge exchange between researchers, promoting local research work, exploring potential collaborations, and fostering closer ties with other research universities."
history2: "In 2014, the Symposium has registered more than 150 student participants, half of which represent participants from 9 other different local universities/research institutes. In 2016, the symposium was held with more registered participants, including external participants who were from 13 universities and a government agency. A new scope was introduced in MSS 2016, covering a total of 6 major life sciences branches and were presented over 3-day periods. The Symposium had received overwhelming positive feedback from the participants. In 2018, an intervarsity symposium which served as a promotional event to highlight the capabilities of HDR students of Monash University Malaysia in producing quality research outputs and the dissemination of their scientific findings to a broader audience. In 2021, the Symposium continued its legacy by expanding the event and introducing a new science category, “Science Communication and Safety.” This addition aimed to broaden the scope of the symposium and address emerging trends in the scientific community. This approach was also carried forward in 2022, with the same focus on expanding the event and strengthening this category to further engage participants and enhance the overall impact of the symposium."
history3: "For MSS 2025, we aim to host the Symposium as an international platform that brings together students, researchers, and experts from around the world. The event will feature a diverse array of research topics, showcasing the innovative work being carried out at Monash University Malaysia. Aligned with the university's Impact 2030 initiative, the Symposium will provide an opportunity for young scientists and postgraduate students to present their findings, engage in meaningful discussions, and connect with leading professionals in their respective fields. Through this event, we will highlight Monash University's ongoing contributions to global scientific advancement and foster collaboration between local and international research communities."

# Event Sponsors Block
sponsorsTitle: "Event Sponsors"
sponsorsDescription: "We are proud to be supported by our generous sponsors who help make MSS 2025 possible. Their contributions enable us to deliver an impactful and memorable event."

sponsorGroups:
  - group: "Event Organiser"
    elements:
      - name: "Monash University Malaysia"
        logo: "MUM-logo.png"
        link: "https://www.monash.edu.my/"

  - group: "Platinum Sponsors"
    elements:
      - name: "Eppendorf Asia Pacific"
        logo: "Eppendorf-logo.png"
        link: "https://www.eppendorf.com/my-en"
      - name: "Everlife-Chemopharm Group"
        logo: "Chemopharm-logo.jpg"
        link: "https://www.chemopharm.com/"

  - group: "Gold Sponsor"
    elements:
      - name: "Canvio Sdn Bhd"
        logo: "Canvio-logo.png"
        link: "https://www.canvio.net/"

  - group: "Copper Sponsors"
    elements:
      - name: "PaperBox Malaysia Sdn Bhd"
        logo: "PaperBox-logo.png"
        link: "https://www.ourpaperbox.com/"
      - name: "Alpha Gas Solution Sdn Bhd"
        logo: "AGS-logo.png"
        link: "http://www.ags.my/"
      - name: "MC Lab"
        logo: "MCLab-logo.png"
        link: "https://www.mclab.com.my/"

  - group: "Value Sponsors"
    elements:
      - name: "Gene Xpress PLT"
        logo: "GeneXpress-logo.jpg"
        link: "https://www.gene-xpress.com.my/"
      - name: "Nestle Malaysia"
        logo: "Nestle-logo.jpg"
        link: "https://www.nestle.com.my/"


# Guidelines Block
guidelinesTitle: "Submission Guidelines"
guidelines1: "Welcome to Monash Science Symposium (MSS) 2025! Our theme this year is “Innovating for Tomorrow: Scientific Solutions for a Sustainable Future”.
MSS 2025 will feature the following categories:"

guidelines2: "<strong>For full submission guidelines please click the Submission & Format Guidelines button below.</strong>"
abstractSubmissionTitle: "Abstract Submission Guidelines"
abstractSubmissionPoints:
 - {point: "Submit abstracts in English via the registration form using the presenting author's email address."}
 - {point: "Each abstract can only be submitted <strong>once</strong>. Please proofread for spelling, grammar and scientific accuracy before submission; no changes are allowed after the deadline."}
 - {point: "Choose the appropriate topic/field and indicate your preference for presentation type: oral, poster, or either. Acceptance notifications will specify the format."}

guidelinesButton:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSd5MeP9RFuBrG3bQ13-8G_HB810IbFPFHAz-ojSsvQ8uY3ePw/viewform?usp=sharing", text: "Join our mailing list"}
 - {link: "https://shop.monash.edu.my/monash-science-symposium-2025.html", text: "Register now"} 
 - {link: "https://drive.google.com/file/d/1LHJMME20Nko_g__c0IErcqAzqUqS7uoK/view?usp=sharing", text: "Submission & Format Guidelines"}

# Key Dates Block
keyDatesBlockImage: "key-dates.jpg"
keyDates:
 - {date: "14 January 2025", text: "Registration Open"} 
 - {date: "1 May 2025", text: "Early Bird Deadline"}
 - {date: "31 May 2025", text: "Registration for Presenters Closes"}
 - {date: "15-17 July 2025", text: "Symposium dates"}

# Partners Block
partnersTitle: "Sponsors"
partnersDescription: "We would like to thank our sponsor for their generous support:"

# Tickets Block
ticketsTitle: "Ticket prices"
ticketsOffers:
#-
 # name: "Monash Student"
 # price: "136"
 # priceCurrency: "MYR"
 # buyButtonLink: "https://shop.monash.edu.my/monash-science-symposium-2025.html"
 # buyButtonText: "<strong>Register</strong>"
 # earlyBirdRate: true
 # additionalInfo: "<strong>Discount code: 20MSS2025; Valid till 01/05/2025</strong>"
#-  
 # name: "Non-Monash Student"
 # price: "216"
 # priceCurrency: "MYR"
 # buyButtonLink: "https://shop.monash.edu.my/monash-science-symposium-2025.html"
 # buyButtonText: "<strong>Register</strong>"
 # earlyBirdRate: true
 # additionalInfo: "<strong>Discount code: 20MSS2025; Valid till 01/05/2025</strong>"
-  
  name: "Monash Student"
  price: "170"
  priceCurrency: "MYR"
# buyButtonLink: 
  buyButtonText: "<strong>Registration closed</strong>"
  additionalInfo: "<em>Only for Monash students</em>"
-
  name: "Non-Monash Student"
  price: "270"
  priceCurrency: "MYR"
# buyButtonLink:
  buyButtonText: "<strong>Registration closed</strong>"
  additionalInfo: "<em>For students/researchers from other universities/institutions</em>"
-
  name: "Non-Presenters"
  price: "30"
  priceCurrency: "MYR"
  buyButtonLink: "https://shop.monash.edu.my/monash-science-symposium-2025.html"
  buyButtonText: "<strong>Register</strong>"
  additionalInfo: "<em>Not inclusive of food</em>"

# Footer
socialLinks:
  - {link: "https://twitter.com/mss_mum", icon: "twitter"}
  - {link: "https://linkedin.com/in/monash-science-symposium-790b301a1", icon: "linkedin"}
  - {link: "https://www.instagram.com/monash.sciencesymposium/", icon: "instagram"}
  - {link: "https://www.facebook.com/monashsciencesymposium/", icon: "facebook"}
footerBlocks:
 -
  title: "Contact"
  links:
   - {link: "mailto:mum-sciencesymposium@monash.edu", text: "Email us"}
 -
  title: "Past events"
  links:
    - {link: "https://monash-sciencesymposium.github.io/zeppelin/", text: "MSS 2022"}
    - {link: "https://monash-sciencesymposium.github.io/website-2021/", text: "MSS 2021"}
    - {link: "https://monashscience2018.jimdofree.com/", text: "MSS 2018"}
    - {link: "https://monashscience.jimdofree.com/", text: "MSS 2016"}

# Speakers List Block
showSessions: false
